return {
    kinetic_impactor = {
	name                    = [[Kinetic Impactor]],
	alphaDecay              = 0.12,
	alwaysVisible		= false,
	areaOfEffect            = 256,
	cegTag                  = [[gauss_tag_h]],
	craterBoost             = 1,
	craterMult              = 2,
    
	damage                  = {
	    default = 1500,
	},
    
	edgeEffectiveness       = 0.5,
	explosionGenerator      = [[custom:lrpc_expl]],
	model                   = [[wep_m_ajax.s3o]],
	myGravity               = 0.5,
	flightTime              = 100,
	fixedLauncher		= false,
	impulseBoost            = 250,
	impulseFactor           = 0.5,
	interceptedByShieldType = 1,
	range                   = 20000,
	reloadtime              = 8,
	rgbColor                = [[1 0.6 0]],
	startVelocity           = 250,
	separation              = 0.5,
	size                    = 0.8,
	sizeDecay               = -0.1,
	smokeTrail		= false,
	soundHit                = [[explosion/ex_large2]],
	--soundStart              = [[weapon/gauss_fire]],
	stages                  = 32,
	--thickness		= 4,
	--coreThickness		= 2,
	turret                  = true,
	weaponType              = [[LaserCannon]],
	weaponVelocity          = 250,
    },
}
