{
	[1] = {
		["AllyID"] = 0,
		["AllyName"] = [[West]],
		["IsHuman"] = true,
		["IsRequired"] = true,
		["TeamID"] = 0,
		["TeamName"] = [[Player]],
		["Color"] = 5177088,
		["ColorR"] = 0,
		["ColorG"] = 255,
		["ColorB"] = 78,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
	[2] = {
		["AllyID"] = 0,
		["AllyName"] = [[West]],
		["IsHuman"] = false,
		["IsRequired"] = false,
		["TeamID"] = 1,
		["TeamName"] = [[Ally]],
		["Color"] = 16711779,
		["ColorR"] = 99,
		["ColorG"] = 0,
		["ColorB"] = 255,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
	[3] = {
		["AllyID"] = 1,
		["AllyName"] = [[East]],
		["IsHuman"] = false,
		["IsRequired"] = false,
		["TeamID"] = 2,
		["TeamName"] = [[Enemy]],
		["Color"] = 255,
		["ColorR"] = 255,
		["ColorG"] = 0,
		["ColorB"] = 0,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
}